# fly.toml app configuration file generated for val-stats-server on 2023-11-28T19:17:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "val-stats-server"
primary_region = "yyz"

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
